# Generated by Django 3.2.20 on 2026-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0023_printsettings_crop_whitespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsettings',
            name='grid_size',
            field=models.IntegerField(choices=[(28, '28 mm ~ 1.1 inch'), (24, '24 mm ~ 1 inch'), (18, '18 mm ~ 3/4 inch'), (12, '12 mm ~ 1/2 inch')], default=24),
        ),
    ]
