# Generated by Django 3.2.20 on 2026-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0023_alter_printsettings_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsettings',
            name='crop_whitespace',
            field=models.BooleanField(default=False),
        ),
    ]
